export interface RawOrder {
  asset: string;
  side: string;
  amount: number;
  leverage: number;
  userStopLossPrice?: number;
  userTakeProfitPrice?: number;
  assetType: string;
  upfrontFee?: number;
}

export interface TradingResponse {
  status: string;
  error?: string;
  body: any;
}

export const availableAssets = [
  'BLURUSDT',
  'FTMUSDT',
  'AAVEUSDT',
  'COMPUSDT',
  'UNIUSDT',
  'BITUSDT',
  'CRVUSDT',
  'OPUSDT',
  'MKRUSDT',
  'GMXUSDT',
  'SNXUSDT',
  'ZECUSDT',
  '1INCHUSDT',
  'DYDXUSDT',
  'BNBUSDT',
  'SUSHIUSDT',
  'DASHUSDT',
  'ZRXUSDT',
  'ENSUSDT',
  'AVAXUSDT',
  'GRTUSDT',
  'APTUSDT',
  'BTCUSDT',
  'DOGEUSDT',
  'ETHUSDT',
  'XRPUSDT',
  'SOLUSDT',
  'LTCUSDT',
  'LINKUSDT',
  'ADAUSDT',
  'TRXUSDT',
  'DOTUSDT',
  'MATICUSDT',
  'APEUSDT',
  'ARBUSDT',
  'BANDUSDT',
  'CTSIUSDT',
  '1000PEPEUSDT',
  '10000LADYSUSDT',
  '1000FLOKIUSDT',
  'AXSUSDT',
  'MANAUSDT',
  'SANDUSDT',
  'LINAUSDT',
  'RNDRUSDT',
  'KDAUSDT',
  'INJUSDT',
  'FTTUSDT',
  'RLBUSDT',
  'WLDUSDT',
  'BCHUSDT',
  'BITUSDT',
];

export const assetNameToUserAssetName: Record<string, string> = {
  BLURUSDT: 'BLUR/USD',
  FTMUSDT: 'FTM/USD',
  AAVEUSDT: 'AAVE/USD',
  COMPUSDT: 'COMP/USD',
  UNIUSDT: 'UNI/USD',
  BITUSDT: 'BIT/USD',
  CRVUSDT: 'CRV/USD',
  OPUSDT: 'OP/USD',
  MKRUSDT: 'MKR/USD',
  GMXUSDT: 'GMX/USD',
  SNXUSDT: 'SNX/USD',
  ZECUSDT: 'ZEC/USD',
  '1INCHUSDT': '1INCH/USD',
  DYDXUSDT: 'DYDX/USD',
  BNBUSDT: 'BNB/USD',
  SUSHIUSDT: 'SUSHI/USD',
  DASHUSDT: 'DASH/USD',
  ZRXUSDT: 'ZRX/USD',
  ENSUSDT: 'ENS/USD',
  AVAXUSDT: 'AVAX/USD',
  GRTUSDT: 'GRT/USD',
  APTUSDT: 'APT/USD',
  BTCUSDT: 'BTC/USD',
  DOGEUSDT: 'DOGE/USD',
  ETHUSDT: 'ETH/USD',
  XRPUSDT: 'XRP/USD',
  SOLUSDT: 'SOL/USD',
  LTCUSDT: 'LTC/USD',
  LINKUSDT: 'LINK/USD',
  ADAUSDT: 'ADA/USD',
  TRXUSDT: 'TRX/USD',
  DOTUSDT: 'DOT/USD',
  MATICUSDT: 'MATIC/USD',
  APEUSDT: 'APE/USD',
  ARBUSDT: 'ARB/USD',
  BANDUSDT: 'BAND/USD',
  CTSIUSDT: 'CTSI/USD',
  '1000PEPEUSDT': 'PEPE/USD',
  '10000LADYSUSDT': 'LADYS/USD',
  '1000FLOKIUSDT': 'FLOKI/USD',
  AXSUSDT: 'AXS/USD',
  MANAUSDT: 'MANA/USD',
  SANDUSDT: 'SAND/USD',
  LINAUSDT: 'LINA/USD',
  RNDRUSDT: 'RNDR/USD',
  KDAUSDT: 'KDA/USD',
  INJUSDT: 'INJ/USD',
  FTTUSDT: 'FTT/USD',
  RLBUSDT: 'RLB/USD',
  WLDUSDT: 'WLD/USD',
  BCHUSDT: 'BCH/USD',
};

export const userAssetNameToAssetName: Record<string, string> = {
  'BLUR/USD': 'BLURUSDT',
  'FTM/USD': 'FTMUSDT',
  'AAVE/USD': 'AAVEUSDT',
  'COMP/USD': 'COMPUSDT',
  'UNI/USD': 'UNIUSDT',
  'BIT/USD': 'BITUSDT',
  'CRV/USD': 'CRVUSDT',
  'OP/USD': 'OPUSDT',
  'MKR/USD': 'MKRUSDT',
  'GMX/USD': 'GMXUSDT',
  'SNX/USD': 'SNXUSDT',
  'ZEC/USD': 'ZECUSDT',
  '1INCH/USD': '1INCHUSDT',
  'DYDX/USD': 'DYDXUSDT',
  'BNB/USD': 'BNBUSDT',
  'SUSHI/USD': 'SUSHIUSDT',
  'DASH/USD': 'DASHUSDT',
  'ZRX/USD': 'ZRXUSDT',
  'ENS/USD': 'ENSUSDT',
  'AVAX/USD': 'AVAXUSDT',
  'GRT/USD': 'GRTUSDT',
  'APT/USD': 'APTUSDT',
  'BTC/USD': 'BTCUSDT',
  'DOGE/USD': 'DOGEUSDT',
  'ETH/USD': 'ETHUSDT',
  'XRP/USD': 'XRPUSDT',
  'SOL/USD': 'SOLUSDT',
  'LTC/USD': 'LTCUSDT',
  'LINK/USD': 'LINKUSDT',
  'ADA/USD': 'ADAUSDT',
  'TRX/USD': 'TRXUSDT',
  'DOT/USD': 'DOTUSDT',
  'MATIC/USD': 'MATICUSDT',
  'APE/USD': 'APEUSDT',
  'ARB/USD': 'ARBUSDT',
  'BAND/USD': 'BANDUSDT',
  'CTSI/USD': 'CTSIUSDT',
  'PEPE/USD': '1000PEPEUSDT',
  'LADYS/USD': '10000LADYSUSDT',
  'FLOKI/USD': '1000FLOKIUSDT',
  'AXS/USD': 'AXSUSDT',
  'MANA/USD': 'MANAUSDT',
  'SAND/USD': 'SANDUSDT',
  'LINA/USD': 'LINAUSDT',
  'RNDR/USD': 'RNDRUSDT',
  'KDA/USD': 'KDAUSDT',
  'INJ/USD': 'INJUSDT',
  'FTT/USD': 'FTTUSDT',
  'RLB/USD': 'RLBUSDT',
  'WLD/USD': 'WLDUSDT',
  'BCH/USD': 'BCHUSDT',
};

export const existingStocksAssetList = [
  'SNAP',
  'SPY',
  'TSLA',
  'AAPL',
  'MSFT',
  'AMZN',
  'GOOGL',
  'META',
  'COIN',
  'VIXM',
  'VIXY',
  'SQQQ',
  'TQQQ',
  'NVDA',
  'SOXL',
  'LABU',
  'SH',
  'XLF',
  'EEM',
  'HYG',
  'SPXU',
  'FXI',
  'XLE',
  'IWM',
  'GDX',
  'EFA',
  'SPXS',
  'VEA',
  'LQD',
  'TLT',
  'SLV',
  'BBBY',
  'HOOD',
  'DIS',
  'ZM',
  'PYPL',
  'DKNG',
  'UBER',
  'BABA',
  'PLTR',
  'GME',
  'AMC',
  'TGT',
  'NFLX',
  'JPM',
  'GS',
  'BAC',
  'WFC',
  'C',
  'MS',
  'COF',
  'SIVB',
  'SI',
  'SBNY',
  'FRC',
  'CS',
  'NKE',
  'FCNCA',
  'KMX',
  'DOCU',
  'MANU',
  'AI',
  'NIO',
  'CVNA',
  'AFRM',
  'SOFI',
  'AMD',
  'BBBY',
  'PLD',
  'AMT',
  'EQIX',
];

export const STOCK_MARKET_TIME = {
  openTimeUtc: '13:30',
  closeTimeUtc: '19:55',
};

export const STOCK_MARKET_DAYS_OFF = [
  {
    dateObj: { month: 2, day: 20 },
    reason: {
      title: `Due to Presidents' Day, stocks are currently closed for trading.`,
      subtitle: `The markets will be open this week from Tuesday - Friday from ${STOCK_MARKET_TIME.openTimeUtc} UTC to  ${STOCK_MARKET_TIME.closeTimeUtc} UTC.`,
    },
  },
  {
    dateObj: { month: 4, day: 7 },
    reason: {
      title: `The stocks are currently closed for trading today.`,
      subtitle: ` The markets will be open next week from Monday - Friday from ${STOCK_MARKET_TIME.openTimeUtc} UTC to  ${STOCK_MARKET_TIME.closeTimeUtc} UTC.`,
    },
  },
  {
    dateObj: { month: 5, day: 29 },
    reason: {
      title: `Due to the holiday, stocks are currently closed for trading. `,
      subtitle: `The markets will be open this week from Tuesday - Friday from ${STOCK_MARKET_TIME.openTimeUtc} UTC to  ${STOCK_MARKET_TIME.closeTimeUtc} UTC.`,
    },
  },
  {
    dateObj: { month: 6, day: 19 },
    reason: {
      title: `Stock markets are closed today`,
      subtitle: `The markets will be open this week from Tuesday - Friday from ${STOCK_MARKET_TIME.openTimeUtc} UTC to  ${STOCK_MARKET_TIME.closeTimeUtc} UTC.`,
    },
  },
];
